[package]
name = "aircraft_engine_prediction"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
ndarray = "0.15"
ndarray-csv = "0.5"
ndarray-stats = "0.5"
plotters = "0.3.4"
rand = "0.8"
smartcore = { version = "0.4.0", features = ["ndarray-bindings"] }